# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deck_of_cards',
                'doc_host': 'https://isados.github.io',
                'git_url': 'https://github.com/isados/deck_of_cards',
                'lib_path': 'deck_of_cards'},
  'syms': {'deck_of_cards.core': {'deck_of_cards.core.foo': ('core.html#foo', 'deck_of_cards/core.py')}}}
